### ISSUE TITLE
Thelio R2 listed as unsupported

### ISSUE THREAD

**Issue by jcrusing** [system76/thelio-io-windows#5]
I realize this is a WIP, is Thelio R2 supported? Fails on service start:

From Application event log:

unsupported sys_vendor 'System76' and product_version 'thelio-r2'
Custom {
    kind: Other,
    error: "unsupported sys_vendor \'System76\' and product_version \'thelio-r2\'",
}

From System Event Log:
The System76 Thelio Io service terminated unexpectedly.  It has done this 3 time(s).

**Comment by jcrusing** [comment]
Found the line in main.rs limiting it to Mira.

**Comment by draeath** [comment]
[If anyone else needs this.](../blob/264b41a1fc7e02a76cd7da93fa34728506b503f5/src/main.rs#L89-L92)

(if you do not use 264b41a1fc7e02a76cd7da93fa34728506b503f5 your line numbers may differ)

Thanks for details... 😐

**Comment by jcrusing** [comment]
Didn’t add the details because I wasn’t sure if this would be a good thing or not. If the fan curves are specific for the Mira, it might have different impacts on the other cases that have different cooling characteristics. 

@jackpot51 or someone from System76 should weigh in there.

**Comment by draeath** [comment]
The fan curve seems identical to the Linux driver, so while I would be worried about other things... not so much the fan profile.

As far as I'm aware there's only the one I/O board, identical between models?

Would be nice to get some official word though.

**Comment by draeath** [comment]
Oh I should mention there are other fan profiles defined, such as the HEDT?

Can we keep this issue open? It's still outstanding as they have a bunch of thelio models and this driver only has the one in it.

**Comment by jcrusing** [comment]
Agreed, reopening. If nothing else, to get some official guidance.

**Comment by draeath** [comment]
I've done a little digging and the only model-specific stuff I can find in the [Linux daemon](https://github.com/pop-os/system76-power/tree/master/src) is the fan profile.

You can see the model-to-profile mapping [here](https://github.com/pop-os/system76-power/blob/79b02d499c38b16470a516047d4ed9af862fdbaa/src/fan.rs#L33-L39) and the fan profiles [here](https://github.com/pop-os/system76-power/blob/79b02d499c38b16470a516047d4ed9af862fdbaa/src/fan.rs#L223-L276)

If they're open to PRs, I could actually go and make sure the fan curves are identical and add the missing entries? Though I can't actually test anything myself, yet.

Are you willing to give it a shot, if I forked and added the change?

Interesting to note that on the Linux driver they just fail to the standard curve instead of bailing out entirely. Also maybe interesting to see that the mira is absent over there?

----

In the very least though this tells you which profile to use for your hardware 🤣

**Comment by jcrusing** [comment]
I already moved back to Pop_OS full time on the Thelio I have given Proton's  to the point that I no longer need Windows on this desktop, otherwise I'd be willing to test myself. FWIW, I just removed the model check and the Mira profile's didn't seem to cause my system to run hotter than usual, which is saying a lot with a Ryzen 3900XT and a RX 5700XT in the Thelio. :smile:

**Comment by draeath** [comment]
I received my hardware today, so I should be able to play with this myself soonish :)

**Comment by draeath** [comment]
I had a different system/version string (see #7) and had to bump the rust compiler version to use the syntax that allowed a minimal code change...

But anyway, it worked. [If you want to see what that looks like, the commit is on my fork currently.](https://github.com/draeath/thelio-io-windows/commit/3f6255cc41b4e66cae5ea00a8fd181ac9b0ea1c3) Assuming a positive result from #7 I plan to submit a PR.
